### PR TITLE
Feature/brads deep thoughts

### PR DESCRIPTION
**Pull request by bradpearson**

### CODE REVIEW

**Comment by mewdriller** [comment]
It looks like there are two of the light NetJets backgrounds in the diff. Should we be using one over the other?

**Comment by mewdriller** [comment]
LGTM @bradpearson. :ship: 

@csteinert and I will have to update our slides to use the backgrounds properly once this is all merged in.

**Comment by bradpearson** [comment]
@mewdriller - Yea, use the one with a 2 at the end. I removed those black bars on the sides and forgot to remove the old one.

**Comment by mewdriller** [comment]
:speak_no_evil: It looks like my branch had some conflicts. Sorry about that!

**Pull request merged**
